services:
  - type: worker
    name: ai-tools-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: COOLDOWN_DAYS
        value: "5"
